language: java
matrix:
  include:
    - os: osx
      osx_image: xcode12.5
    - os: osx
      osx_image: xcode12.4
    - os: osx
      osx_image: xcode12.3
    - os: osx
      osx_image: xcode12.2
script:
  - mvn test -Dtest=ConnectionIntegrationTest#testConnectionFailsWhenUserSuppliesIllegalProperties -Dmaven.test.redirectTestOutputToFile=false -Dproton.trace.frames=true
cache:
  directories:
  - $HOME/.m2
before_cache:
  - rm -rf $HOME/.m2/repository/org/apache/qpid/*
